---
title: "Script Réunion Pierre Martre"
author: "Nicolas SALAS"
date: '2022-05-31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(tidyverse)
library(lme4)
library(Rcpp)
library(lmerTest)
library(car)
library(ggplot2)
library(cowplot)
library(deeplr)
library(multcompView)
library(lsmeans)
library(emmeans)
library(sommer)
```

#Gestion des données: 

``` {r}
data_final<-as_data_frame(read.csv("Mesures_neighbors_31052022.tsv",header=TRUE,sep="\t"))


data_final<-data_final[-c(16)]
data_final<-data_final[-c(6)]


#Ajout colonne voisin

data_final_pair = data_final[c(1:270)*2,]
data_final_impair = data_final[c((1:270)*2 -1),]
data_final_pair$voisin = data_final_impair$plante_genotype
data_final_pair$poids_graine_voisin=data_final_impair$poids_graine
data_final_impair$voisin = data_final_pair$plante_genotype
data_final_impair$poids_graine_voisin=data_final_pair$poids_graine
data_final = as.data.frame(rbind(data_final_pair,data_final_impair))
rm(data_final_impair)
rm(data_final_pair)


#Modifications Ligne et Colonne pour coller au design

data_final[data_final$Bloc %in% c(2,4,6),]$Ligne = data_final[data_final$Bloc %in% c(2,4,6),]$Ligne + 11
data_final[data_final$Bloc %in% c(5,6),]$Colonne = data_final[data_final$Bloc %in% c(5,6),]$Colonne + 18
data_final[data_final$Bloc %in% c(3,4),]$Colonne = data_final[data_final$Bloc %in% c(3,4),]$Colonne + 9
table(data_final$Ligne,data_final$Bloc)

#Ajout de la colonne RHT_rht

for (elt in (1:nrow(data_final))){
  if (data_final$plante_genotype[elt]%in%c("114","235","329","376","395","482","89")){
    data_final$RHT_rht[elt]="rht"
  }
  else{
    data_final$RHT_rht[elt]="RHT"
  }
}

#AJout de la colonne RHT_voisin

for (elt in (1:nrow(data_final))){
  if (data_final$voisin[elt]%in%c("114","235","329","376","395","482","89")){
    data_final$RHT_voisin[elt]="rht"
  }
  else{
    data_final$RHT_voisin[elt]="RHT"
  }
}

#Ajout de la colonne "Structuration du design"

for (elt in (1:nrow(data_final))){
  if (data_final$plante_genotype[elt]%in%c("235","114","329","376","395")){
    data_final$Structuration_design[elt]=1
  }
  else if (data_final$plante_genotype[elt]%in%c("412","165","131","74","130")){
    data_final$Structuration_design[elt]=2
  }
  else{
    data_final$Structuration_design[elt]=3
  }
}

#Nettoyage du jeu de données 

data<-data_final[,-c(2,3,16:19)]


# elimnation des pots dans lesquels au moins une des plantes a mal poussé

#On elimine les pots pour lesquels on n'a pas de données sur la feuille 1
liste0<-which(is.na(data$Longueur_feuille_1))
liste1<-which(data$Couple%in%data$Couple[liste0])
data<-data[-liste1,]

# pas de données sur la Longueur_feuille_2

liste2<-which(is.na(data$Longueur_feuille_2))
liste3<-which(data$Couple %in% data$Couple[liste2])
data<-data[-liste3,]


# Elimination des pots pour lesquesls au moins une plante n'a  pas de donnees de biomasse
liste4<-which(is.na(data$Biomasse_seche))
liste5<-which(data$Couple%in%data$Couple[liste4])
data<-data[-liste5,]

# Elimination des pots avec une plante chétive
liste6<-which(data$Biomasse_seche<24)
liste7<-which(data$Couple%in%data$Couple[liste6])
data<-data[-liste7,]

#Elimination des pots avec un poids de graine inconnu
liste8<-which(is.na(data$poids_graine))
liste9<-which(data$Couple%in%data$Couple[liste8])
data<-data[-liste9,]

#Fixation des types de données 

data<-data %>%
  mutate(Bloc=as.factor(Bloc),
         plante_genotype=as.factor(plante_genotype),
         voisin=as.factor(voisin),
         Condition_hydrique=as.factor(Condition_hydrique),
         Bloc = as.factor(Bloc),
         plante_genotype= as.factor(plante_genotype),
         Condition_hydrique =as.factor(Condition_hydrique),
         Monoculture_Couple =as.factor(Monoculture_Couple),
         dvoisin =as.factor(voisin),
         Ligne=as.factor(Ligne),
         Colonne=as.factor(Colonne),
         Structuration_design=as.factor(Structuration_design),
         Bloc_M = as.factor(paste0(Bloc,Condition_hydrique)),
         Surface_feuille_2 = Longueur_feuille_2 * 0.73 * Largeur_feuille_2,
         Surface_feuille_1 = Longueur_feuille_1 * 0.73 * Largeur_feuille_1,
         log_lf2 = log(Longueur_feuille_2),
         sqrt_lf2 = sqrt(Longueur_feuille_2),
         log_sf2 = log(Surface_feuille_2),
         log_sf1 = log(Surface_feuille_1),
         sqrt_sf2 = sqrt(Surface_feuille_2),
         sqrt_sf1 = sqrt(Surface_feuille_1))

```

```{r}
#Outliers et Visualisation 

#Outliers Longueur_feuille_1

Quant_sup_lf2<-quantile(data$Longueur_feuille_1,0.99)
Quant_inf_lf2<-quantile(data$Longueur_feuille_1,0.01)
outlier<-which(data$Longueur_feuille_1<Quant_inf_lf2)

hist_lf2<-ggplot(data,aes(Longueur_feuille_1))+
  geom_histogram(aes(y=..density..),color="Blue",fill="white",binwidth =1.5)+
  geom_density(fill="Red",alpha=0.2)+
  geom_vline(aes(xintercept=Quant_inf_lf2),color="red")+
  geom_vline(aes(xintercept=Quant_sup_lf2),color="red")
###Prise en compte que des outliers < au quantile 1%

#Outliers Largeur_feuille_2 (Pas vraiment utilisable pour analyse)

Quant_sup_laf1<-quantile(data$Largeur_feuille_2,0.99)
Quant_inf_laf1<-quantile(data$Largeur_feuille_2,0.01)
outlier_laf1_idx<-which(data$Largeur_feuille_2<Quant_inf_laf1|data$Largeur_feuille_2>Quant_sup_laf1)

hist_laf1<-ggplot(data,aes(Largeur_feuille_2))+
  geom_histogram(aes(y=..density..),color="Blue",fill="white",binwidth =1.5)+
  geom_density(fill="Red",alpha=0.2)+
  geom_vline(aes(xintercept=Quant_inf_laf1),color="red")+
  geom_vline(aes(xintercept=Quant_sup_laf1),color="red")

#Outliers Longueur_feuille_1

Quant_sup_lf1<-quantile(data$Longueur_feuille_1,0.99)
Quant_inf_lf1<-quantile(data$Longueur_feuille_1,0.01)
outlier_lf1_idx<-which(data$Longueur_feuille_1<Quant_inf_lf1|data$Longueur_feuille_1>Quant_sup_lf1)

hist_lf1<-ggplot(data,aes(Longueur_feuille_1))+
  geom_histogram(aes(y=..density..),color="Blue",fill="white",binwidth =1.5)+
  geom_density(fill="Red",alpha=0.2)+
  geom_vline(aes(xintercept=Quant_inf_lf1),color="red")+
  geom_vline(aes(xintercept=Quant_sup_lf2),color="red")

#Outliers Largeur_feuille_1 (Pas vraiment utilisable pour analyse)

Quant_sup_laf1<-quantile(data$Largeur_feuille_1,0.99)
Quant_inf_laf1<-quantile(data$Largeur_feuille_1,0.01)
outlier_laf1_idx<-which(data$Largeur_feuille_1<Quant_inf_laf1|data$Largeur_feuille_1>Quant_sup_laf1)

hist_laf1<-ggplot(data,aes(Largeur_feuille_1))+
  geom_histogram(aes(y=..density..),color="Blue",fill="white",binwidth =1.5)+
  geom_density(fill="Red",alpha=0.2)+
  geom_vline(aes(xintercept=Quant_inf_laf1),color="red")+
  geom_vline(aes(xintercept=Quant_sup_laf1),color="red")

#Outliers Biomasse sèche

Quant_sup_b<-quantile(data$Biomasse_seche,0.99)
Quant_inf_b<-quantile(data$Biomasse_seche,0.01)
outlier_b_idx<-which(data$Biomasse_seche<Quant_inf_b|data$Biomasse_seche>Quant_sup_b)

hist_b<-ggplot(data,aes(Biomasse_seche))+
  geom_histogram(aes(y=..density..),color="Blue",fill="white",binwidth =1.5)+
  geom_density(fill="Red",alpha=0.2)+
  geom_vline(aes(xintercept=Quant_inf_b),color="red")+
  geom_vline(aes(xintercept=Quant_sup_b),color="red")

outlier<-intersect(outlier,intersect(outlier_b_idx,outlier_lf1_idx))

#Etude de la longueur feuille 2
#Modèles fixes (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mod0<- lm(Longueur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine,
           data=data)
summary(mod0)
anova(mod0)

mod0.1<-lm(Longueur_feuille_2~
           Bloc_M+
           Structuration_design+
           poids_graine,
           data=data[-outlier,])
summary(mod0.1)
anova(mod0.1)

mod1<-lm(Longueur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype,
           data=data)
summary(mod1)
anova(mod1)

mod1.1<-lm(Longueur_feuille_2~
           Bloc_M+
           Structuration_design+
           poids_graine+
           plante_genotype,
           data=data[-outlier,])

summary(mod1.1)
anova(mod1.1)

mod2 <- lm(Longueur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data)
summary(mod2)
anova(mod2)

mod2.1<-lm(Longueur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data[-outlier,])
summary(mod2.1)
anova(mod2.1)

mod3 <- lm(Longueur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data)
summary(mod3)
anova(mod3)

mod3.1<-lm(Longueur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data[-outlier,])
summary(mod3.1)
anova(mod3.1)

mod4 <- lm(Longueur_feuille_2~
      
           plante_genotype*
           voisin,
           data=data[data$Structuration_design == "3",])
summary(mod4)
anova(mod4)

mod4.1<-lm(Longueur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data[-outlier,])
x = summary(mod4.1)
anova(mod4.1)

#Récupération des DGE et IGE marginaux pour les modèles avec outliers.

marg_dge<-emmeans(mod4,~plante_genotype)
marg_ige<-emmeans(mod4,~voisin)
marg_inter<-emmeans(mod4.1,~plante_genotype:voisin)
marg_inter2<-emmeans(mod4.1,~plante_genotype*voisin)
head(summary(marg_inter))
head(summary(marg_inter2))
a<-as.vector(as.character(summary(marg_dge)$plante_genotype))
b<-as.vector(as.character(summary(marg_dge)$emmean ))
c<-as.vector(as.character(summary(marg_inter)$plante_genotype))
d<-as.vector(as.character(summary(marg_inter)$voisin))
e<-as.vector(as.character(summary(marg_inter)$emmean))

mean_inter<-mean_dge<-as.data.frame(cbind(c,d,as.numeric(e)))
names(mean_inter)<-c("EPO","VOISIN","ESTIMATE")
df1 = mean_inter[paste(mean_inter$EPO,mean_inter$VOISIN) %in% paste(t(combn(unique(mean_inter$EPO),2))[,1],t(combn(unique(mean_inter$EPO),2))[,2]),]
df2 = mean_inter[paste(mean_inter$EPO,mean_inter$VOISIN) %in% paste(t(combn(unique(mean_inter$EPO),2))[,2],t(combn(unique(mean_inter$EPO),2))[,1]),]
df1 = na.omit(df1)
df2 = na.omit(df2)
df = merge(df1,df2,by.x = c(1,2),by.y = c(2,1))
mean_inter<-na.omit(mean_inter)
plot(as.numeric(df$ESTIMATE.x),as.numeric(df$ESTIMATE.y))

mean_dge<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_dge)<-c("EPO", "DGE")
mean_dge$DGE <- as.numeric(mean_dge$DGE)

a<-as.vector(as.character(summary(marg_ige)$voisin))
b<-as.vector(as.character(summary(marg_ige)$emmean ))
mean_ige<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_ige)<-c("EPO", "IGE")

BLUE<-merge(mean_dge, mean_ige, by.x=1, by.y=1 )
BLUE$DGE<-as.numeric(BLUE$DGE)
BLUE$IGE<-as.numeric(BLUE$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE$DGE,BLUE$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE))
abline(coef,col = "red")
cor.test(BLUE$DGE, BLUE$IGE)

##Récupération des DGE et IGE marginaux pour les modèles sans outliers.

marg_dge.1<-emmeans(mod4.1,~plante_genotype)
marg_ige.1<-emmeans(mod4.1,~voisin)

a.1<-as.vector(as.character(summary(marg_dge.1)$plante_genotype))
b.1<-as.vector(as.character(summary(marg_dge.1)$emmean ))

mean_dge.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_dge.1)<-c("EPO", "DGE")
mean_dge.1$DGE <- as.numeric(mean_dge.1$DGE)

a.1<-as.vector(as.character(summary(marg_ige.1)$voisin))
b.1<-as.vector(as.character(summary(marg_ige.1)$emmean ))
mean_ige.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_ige.1)<-c("EPO", "IGE")

BLUE.1<-merge(mean_dge.1, mean_ige.1, by.x=1, by.y=1 )
BLUE.1$DGE<-as.numeric(BLUE.1$DGE)
BLUE.1$IGE<-as.numeric(BLUE.1$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE.1$DGE,BLUE.1$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE.1))
abline(coef,col = "red")
cor.test(BLUE.1$DGE, BLUE.1$IGE)

#Modèles mixtes sommer (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mmod0 <- mmer(Longueur_feuille_2 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data)
summary(mmod0)
anova(mmod0)

mmod0.1 <- mmer(Longueur_feuille_2 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod0.1)
anova(mmod0.1)

mmod1 <- mmer(Longueur_feuille_2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod1)
anova(mmod1)

mmod1.1 <- mmer(Longueur_feuille_2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod1.1)
anova(mmod1.1)

mmod2 <- mmer(Longueur_feuille_2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data)
summary(mmod2)
anova(mmod2)

mmod2.1 <- mmer(Longueur_feuille_2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod2.1)
anova(mmod2.1)

mmod3 <- mmer(Longueur_feuille_2 ~ Structuration_design + Bloc_M,
                 random = ~ gvs(plante_genotype,voisin)+ plante_genotype:voisin,
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod3)
anova(mmod3)

mmod3.1 <- mmer(Longueur_feuille_2 ~ Structuration_design + Bloc_M,
                 random = ~ gvs(plante_genotype,voisin) ,
                 rcov = ~ units, iters = 10,
                 data = data[-outlier,])
summary(mmod3.1)
anova(mmod3.1)
cor.test(mmod3.1$U$`plante_genotype:plante_genotype`$Longueur_feuille_2,mmod3.1$U$`voisin:voisin`$Longueur_feuille_2)
#Calcul de la correlation pour les modèles à covariance

#Modèle avec outlier

vDGE<-summary(mmod3)$varcomp[[1]][1]
covDGE.IGE<-summary(mmod3)$varcomp[[1]][2]
vIGE<-summary(mmod3)$varcomp[[1]][3]
rDGE_IGE<-covDGE.IGE / (vDGE * vIGE)**.5

#Modèle sans outlier
vDGE.1<-summary(mmod3.1)$varcomp[[1]][1]
covDGE.IGE.1<-summary(mmod3.1)$varcomp[[1]][2]
vIGE.1<-summary(mmod3.1)$varcomp[[1]][3]
rDGE_IGE.1<-covDGE.IGE.1 / (vDGE.1 * vIGE.1)**.5

#Modèles mixtes lme4 (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)


lmod1 <- lmer(Longueur_feuille_2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data)
summary(lmod1)
anova(lmod1)

lmod1.1 <- lmer(Longueur_feuille_2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data[-outlier,])
summary(lmod1.1)
anova(lmod1.1)

lmod2 <- lmer(Longueur_feuille_2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data)
summary(lmod2)
anova(lmod2)

lmod2.1 <- lmer(Longueur_feuille_2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data[-outlier,])
summary(lmod2.1)
anova(lmod2.1)

lmod3 <- lmer(Longueur_feuille_2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
            +(1|plante_genotype:voisin)
              , data = data)
summary(lmod3)
anova(lmod3)

lmod3.1 <- lmer(Longueur_feuille_2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
            + (1|plante_genotype:voisin)
              , data = data[-outlier,])

summary(lmod3.1)
anova(lmod3.1)

#Plot BLUP IGE vs DGE et correlation avec outlier

BLUP<-merge(ranef(lmod3)$plante_genotype, ranef(lmod3)$voisin, by.x=0, by.y=0)
names(BLUP)<-c("EPO","DGE","IGE")

plot(BLUP$DGE,BLUP$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP))
abline(coef,col="red")
cor.test(BLUP$DGE,BLUP$IGE)

#Plot BLUP IGE vs DGE et correlation sans outlier

BLUP.1<-merge(ranef(lmod3.1)$plante_genotype, ranef(lmod3.1)$voisin, by.x=0, by.y=0)
names(BLUP.1)<-c("EPO","DGE","IGE")

plot(BLUP.1$DGE,BLUP.1$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP.1))
abline(coef,col="red")
cor.test(BLUP.1$DGE,BLUP.1$IGE)

#Etude de la feuille 1 
#Modèles fixes (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mod0<- lm(Longueur_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine,
           data=data)
summary(mod0)
anova(mod0)

mod0.1<-lm(Longueur_feuille_1~
           Bloc_M+
           Structuration_design+
           poids_graine,
           data=data[-outlier,])
summary(mod0.1)
anova(mod0.1)

mod1<-lm(Longueur_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype,
           data=data)
summary(mod1)
anova(mod1)

mod1.1<-lm(Longueur_feuille_1~
           Bloc_M+
           Structuration_design+
           poids_graine+
           plante_genotype,
           data=data[-outlier,])

summary(mod1.1)
anova(mod1.1)

mod2 <- lm(Longueur_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data)
summary(mod2)
anova(mod2)

mod2.1<-lm(Longueur_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data[-outlier,])
summary(mod2.1)
anova(mod2.1)

mod3 <- lm(Longueur_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data)
summary(mod3)
anova(mod3)

mod3.1<-lm(Longueur_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data[-outlier,])
summary(mod3.1)
anova(mod3.1)

#Récupération des DGE et IGE marginaux pour les modèles avec outliers.

marg_dge<-emmeans(mod3,~plante_genotype)
marg_ige<-emmeans(mod3,~voisin)

a<-as.vector(as.character(summary(marg_dge)$plante_genotype))
b<-as.vector(as.character(summary(marg_dge)$emmean ))

mean_dge<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_dge)<-c("EPO", "DGE")
mean_dge$DGE <- as.numeric(mean_dge$DGE)

a<-as.vector(as.character(summary(marg_ige)$voisin))
b<-as.vector(as.character(summary(marg_ige)$emmean ))
mean_ige<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_ige)<-c("EPO", "IGE")

BLUE<-merge(mean_dge, mean_ige, by.x=1, by.y=1 )
BLUE$DGE<-as.numeric(BLUE$DGE)
BLUE$IGE<-as.numeric(BLUE$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE$DGE,BLUE$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE))
abline(coef,col = "red")
cor.test(BLUE$DGE, BLUE$IGE)

##Récupération des DGE et IGE marginaux pour les modèles sans outliers.

marg_dge.1<-emmeans(mod3.1,~plante_genotype)
marg_ige.1<-emmeans(mod3.1,~voisin)

a.1<-as.vector(as.character(summary(marg_dge.1)$plante_genotype))
b.1<-as.vector(as.character(summary(marg_dge.1)$emmean ))

mean_dge.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_dge.1)<-c("EPO", "DGE")
mean_dge.1$DGE <- as.numeric(mean_dge.1$DGE)

a.1<-as.vector(as.character(summary(marg_ige.1)$voisin))
b.1<-as.vector(as.character(summary(marg_ige.1)$emmean ))
mean_ige.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_ige.1)<-c("EPO", "IGE")

BLUE.1<-merge(mean_dge.1, mean_ige.1, by.x=1, by.y=1 )
BLUE.1$DGE<-as.numeric(BLUE.1$DGE)
BLUE.1$IGE<-as.numeric(BLUE.1$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE.1$DGE,BLUE.1$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE.1))
abline(coef,col = "red")
cor.test(BLUE.1$DGE, BLUE.1$IGE)

#Modèles mixtes sommer (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mmod0 <- mmer(Longueur_feuille_1 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data)
summary(mmod0)
anova(mmod0)

mmod0.1 <- mmer(Longueur_feuille_1 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod0.1)
anova(mmod0.1)

mmod1 <- mmer(Longueur_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod1)
anova(mmod1)

mmod1.1 <- mmer(Longueur_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod1.1)
anova(mmod1.1)

mmod2 <- mmer(Longueur_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data)
summary(mmod2)
anova(mmod2)

mmod2.1 <- mmer(Longueur_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod2.1)
anova(mmod2.1)

mmod3 <- mmer(Longueur_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod3)
anova(mmod3)

mmod3.1 <- mmer(Longueur_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data[-outlier,])
summary(mmod3.1)
anova(mmod3.1)

#Calcul de la correlation pour les modèles à covariance

#Modèle avec outlier

vDGE<-summary(mmod3)$varcomp[[1]][1]
covDGE.IGE<-summary(mmod3)$varcomp[[1]][2]
vIGE<-summary(mmod3)$varcomp[[1]][3]
rDGE_IGE<-covDGE.IGE / (vDGE * vIGE)**.5

#Modèle sans outlier
vDGE.1<-summary(mmod3.1)$varcomp[[1]][1]
covDGE.IGE.1<-summary(mmod3.1)$varcomp[[1]][2]
vIGE.1<-summary(mmod3.1)$varcomp[[1]][3]
rDGE_IGE.1<-covDGE.IGE.1 / (vDGE.1 * vIGE.1)**.5

#Modèles mixtes lme4 (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)


lmod1 <- lmer(Longueur_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data)
summary(lmod1)
anova(lmod1)

lmod1.1 <- lmer(Longueur_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data[-outlier,])
summary(lmod1.1)
anova(lmod1.1)

lmod2 <- lmer(Longueur_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data)
summary(lmod2)
anova(lmod2)

lmod2.1 <- lmer(Longueur_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data[-outlier,])
summary(lmod2.1)
anova(lmod2.1)

lmod3 <- lmer(Longueur_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
              , data = data)
summary(lmod3)
anova(lmod3)

lmod3.1 <- lmer(Longueur_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
              , data = data[-outlier,])

summary(lmod3.1)
anova(lmod3.1)

#Plot BLUP IGE vs DGE et correlation avec outlier

BLUP<-merge(ranef(lmod1)$plante_genotype, ranef(lmod2)$voisin, by.x=0, by.y=0)
names(BLUP)<-c("EPO","DGE","IGE")

plot(BLUP$DGE,BLUP$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP))
abline(coef,col="red")
cor.test(BLUP$DGE,BLUP$IGE)

#Plot BLUP IGE vs DGE et correlation sans outlier

BLUP.1<-merge(ranef(lmod1.1)$plante_genotype, ranef(lmod2.1)$voisin, by.x=0, by.y=0)
names(BLUP.1)<-c("EPO","DGE","IGE")

plot(BLUP.1$DGE,BLUP.1$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP.1))
abline(coef,col="red")
cor.test(BLUP.1$DGE,BLUP.1$IGE)

#Etude de la biomasse sèche 
#Modèles fixes (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mod0<- lm(Biomasse_seche~
           Structuration_design+
           Bloc_M+
           poids_graine,
           data=data)
summary(mod0)
anova(mod0)

mod0.1<-lm(Biomasse_seche~
           Bloc_M+
           Structuration_design+
           poids_graine,
           data=data[-outlier,])
summary(mod0.1)
anova(mod0.1)

mod1<-lm(Biomasse_seche~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype,
           data=data)
summary(mod1)
anova(mod1)

mod1.1<-lm(Biomasse_seche~
           Bloc_M+
           Structuration_design+
           poids_graine+
           plante_genotype,
           data=data[-outlier,])

summary(mod1.1)
anova(mod1.1)

mod2 <- lm(Biomasse_seche~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data)
summary(mod2)
anova(mod2)

mod2.1<-lm(Biomasse_seche~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data[-outlier,])
summary(mod2.1)
anova(mod2.1)

mod3 <- lm(Biomasse_seche~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data)
summary(mod3)
anova(mod3)

mod3.1<-lm(Biomasse_seche~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data[-outlier,])
summary(mod3.1)
anova(mod3.1)

mod4 <- lm(Biomasse_seche~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data)
summary(mod4)
anova(mod4)

mod4.1<-lm(Biomasse_seche~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data[-outlier,])
summary(mod4.1)
anova(mod4.1)


#Récupération des DGE et IGE marginaux pour les modèles avec outliers.

marg_dge<-emmeans(mod1,~plante_genotype)
marg_ige<-emmeans(mod2,~voisin)

a<-as.vector(as.character(summary(marg_dge)$plante_genotype))
b<-as.vector(as.character(summary(marg_dge)$emmean ))

mean_dge<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_dge)<-c("EPO", "DGE")
mean_dge$DGE <- as.numeric(mean_dge$DGE)

a<-as.vector(as.character(summary(marg_ige)$voisin))
b<-as.vector(as.character(summary(marg_ige)$emmean ))
mean_ige<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_ige)<-c("EPO", "IGE")

BLUE<-merge(mean_dge, mean_ige, by.x=1, by.y=1 )
BLUE$DGE<-as.numeric(BLUE$DGE)
BLUE$IGE<-as.numeric(BLUE$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE$DGE,BLUE$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE))
abline(coef,col = "red")
cor.test(BLUE$DGE, BLUE$IGE)

##Récupération des DGE et IGE marginaux pour les modèles sans outliers.

marg_dge.1<-emmeans(mod1.1,~plante_genotype)
marg_ige.1<-emmeans(mod2.1,~voisin)

a.1<-as.vector(as.character(summary(marg_dge.1)$plante_genotype))
b.1<-as.vector(as.character(summary(marg_dge.1)$emmean ))

mean_dge.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_dge.1)<-c("EPO", "DGE")
mean_dge.1$DGE <- as.numeric(mean_dge.1$DGE)

a.1<-as.vector(as.character(summary(marg_ige.1)$voisin))
b.1<-as.vector(as.character(summary(marg_ige.1)$emmean ))
mean_ige.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_ige.1)<-c("EPO", "IGE")

BLUE.1<-merge(mean_dge.1, mean_ige.1, by.x=1, by.y=1 )
BLUE.1$DGE<-as.numeric(BLUE.1$DGE)
BLUE.1$IGE<-as.numeric(BLUE.1$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE.1$DGE,BLUE.1$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE.1))
abline(coef,col = "red")
cor.test(BLUE.1$DGE, BLUE.1$IGE)

#Modèles mixtes sommer (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mmod0 <- mmer(Biomasse_seche ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data)
summary(mmod0)
anova(mmod0)

mmod0.1 <- mmer(Biomasse_seche ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod0.1)
anova(mmod0.1)

mmod1 <- mmer(Biomasse_seche ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod1)
anova(mmod1)

mmod1.1 <- mmer(Biomasse_seche ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod1.1)
anova(mmod1.1)

mmod2 <- mmer(Biomasse_seche ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data)
summary(mmod2)
anova(mmod2)

mmod2.1 <- mmer(Biomasse_seche ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod2.1)
anova(mmod2.1)

mmod3 <- mmer(Biomasse_seche ~ Structuration_design + Bloc_M,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod3)
anova(mmod3)

mmod3.1 <- mmer(Biomasse_seche ~ Structuration_design + Bloc_M,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data[-outlier,])
summary(mmod3.1)
anova(mmod3.1)

#Calcul de la correlation pour les modèles à covariance

#Modèle avec outlier

vDGE<-summary(mmod3)$varcomp[[1]][1]
covDGE.IGE<-summary(mmod3)$varcomp[[1]][2]
vIGE<-summary(mmod3)$varcomp[[1]][3]
rDGE_IGE<-covDGE.IGE / (vDGE * vIGE)**.5

#Modèle sans outlier
vDGE.1<-summary(mmod3.1)$varcomp[[1]][1]
covDGE.IGE.1<-summary(mmod3.1)$varcomp[[1]][2]
vIGE.1<-summary(mmod3.1)$varcomp[[1]][3]
rDGE_IGE.1<-covDGE.IGE.1 / (vDGE.1 * vIGE.1)**.5

#Modèles mixtes lme4 (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)


lmod1 <- lmer(Biomasse_seche ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data)
summary(lmod1)
anova(lmod1)

lmod1.1 <- lmer(Biomasse_seche ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data[-outlier,])
summary(lmod1.1)
anova(lmod1.1)

lmod2 <- lmer(Biomasse_seche ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data)
summary(lmod2)
anova(lmod2)

lmod2.1 <- lmer(Biomasse_seche ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data[-outlier,])
summary(lmod2.1)
anova(lmod2.1)

lmod3 <- lmer(Biomasse_seche ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
              , data = data)
summary(lmod3)
anova(lmod3)

lmod3.1 <- lmer(Biomasse_seche ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
              , data = data[-outlier,])

summary(lmod3.1)
anova(lmod3.1)

#Plot BLUP IGE vs DGE et correlation avec outlier

BLUP<-merge(ranef(lmod1)$plante_genotype, ranef(lmod2)$voisin, by.x=0, by.y=0)
names(BLUP)<-c("EPO","DGE","IGE")

plot(BLUP$DGE,BLUP$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP))
abline(coef,col="red")
cor.test(BLUP$DGE,BLUP$IGE)

#Plot BLUP IGE vs DGE et correlation sans outlier

BLUP.1<-merge(ranef(lmod1.1)$plante_genotype, ranef(lmod2.1)$voisin, by.x=0, by.y=0)
names(BLUP.1)<-c("EPO","DGE","IGE")

plot(BLUP.1$DGE,BLUP.1$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP.1))
abline(coef,col="red")
cor.test(BLUP.1$DGE,BLUP.1$IGE)
```

```{r}
#Etude de la biomasse sèche 
#Modèles fixes (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mod0<- lm(Largeur_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine,
           data=data)
summary(mod0)
anova(mod0)

mod0.1<-lm(Largeur_feuille_1~
           Bloc_M+
           Structuration_design+
           poids_graine,
           data=data[-outlier,])
summary(mod0.1)
anova(mod0.1)

mod1<-lm(Largeur_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype,
           data=data)
summary(mod1)
anova(mod1)

mod1.1<-lm(Largeur_feuille_1~
           Bloc_M+
           Structuration_design+
           poids_graine+
           plante_genotype,
           data=data[-outlier,])

summary(mod1.1)
anova(mod1.1)

mod2 <- lm(Largeur_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data)
summary(mod2)
anova(mod2)

mod2.1<-lm(Largeur_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data[-outlier,])
summary(mod2.1)
anova(mod2.1)

mod3 <- lm(Largeur_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data)
summary(mod3)
anova(mod3)

mod3.1<-lm(Largeur_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data[-outlier,])
summary(mod3.1)
anova(mod3.1)

mod4 <- lm(Largeur_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data)
summary(mod4)
anova(mod4)
shapiro.test(mod4$residuals)

mod4.1<-lm(Largeur_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data[-outlier,])
summary(mod4.1)
anova(mod4.1)


#Récupération des DGE et IGE marginaux pour les modèles avec outliers.

marg_dge<-emmeans(mod1,~plante_genotype)
marg_ige<-emmeans(mod2,~voisin)

a<-as.vector(as.character(summary(marg_dge)$plante_genotype))
b<-as.vector(as.character(summary(marg_dge)$emmean ))

mean_dge<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_dge)<-c("EPO", "DGE")
mean_dge$DGE <- as.numeric(mean_dge$DGE)

a<-as.vector(as.character(summary(marg_ige)$voisin))
b<-as.vector(as.character(summary(marg_ige)$emmean ))
mean_ige<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_ige)<-c("EPO", "IGE")

BLUE<-merge(mean_dge, mean_ige, by.x=1, by.y=1 )
BLUE$DGE<-as.numeric(BLUE$DGE)
BLUE$IGE<-as.numeric(BLUE$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE$DGE,BLUE$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE))
abline(coef,col = "red")
cor.test(BLUE$DGE, BLUE$IGE)

##Récupération des DGE et IGE marginaux pour les modèles sans outliers.

marg_dge.1<-emmeans(mod1.1,~plante_genotype)
marg_ige.1<-emmeans(mod2.1,~voisin)

a.1<-as.vector(as.character(summary(marg_dge.1)$plante_genotype))
b.1<-as.vector(as.character(summary(marg_dge.1)$emmean ))

mean_dge.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_dge.1)<-c("EPO", "DGE")
mean_dge.1$DGE <- as.numeric(mean_dge.1$DGE)

a.1<-as.vector(as.character(summary(marg_ige.1)$voisin))
b.1<-as.vector(as.character(summary(marg_ige.1)$emmean ))
mean_ige.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_ige.1)<-c("EPO", "IGE")

BLUE.1<-merge(mean_dge.1, mean_ige.1, by.x=1, by.y=1 )
BLUE.1$DGE<-as.numeric(BLUE.1$DGE)
BLUE.1$IGE<-as.numeric(BLUE.1$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE.1$DGE,BLUE.1$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE.1))
abline(coef,col = "red")
cor.test(BLUE.1$DGE, BLUE.1$IGE)

#Modèles mixtes sommer (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mmod0 <- mmer(Largeur_feuille_1 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data)
summary(mmod0)
anova(mmod0)

mmod0.1 <- mmer(Largeur_feuille_1 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod0.1)
anova(mmod0.1)

mmod1 <- mmer(Largeur_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod1)
anova(mmod1)

mmod1.1 <- mmer(Largeur_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod1.1)
anova(mmod1.1)

mmod2 <- mmer(Largeur_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data)
summary(mmod2)
anova(mmod2)

mmod2.1 <- mmer(Largeur_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod2.1)
anova(mmod2.1)

mmod3 <- mmer(Largeur_feuille_1 ~ Structuration_design + Bloc_M + poids_graine,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod3)
anova(mmod3)

mmod3.1 <- mmer(Largeur_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data[-outlier,])
summary(mmod3.1)
anova(mmod3.1)

#Calcul de la correlation pour les modèles à covariance

#Modèle avec outlier

vDGE<-summary(mmod3)$varcomp[[1]][1]
covDGE.IGE<-summary(mmod3)$varcomp[[1]][2]
vIGE<-summary(mmod3)$varcomp[[1]][3]
rDGE_IGE<-covDGE.IGE / (vDGE * vIGE)**.5

#Modèle sans outlier
vDGE.1<-summary(mmod3.1)$varcomp[[1]][1]
covDGE.IGE.1<-summary(mmod3.1)$varcomp[[1]][2]
vIGE.1<-summary(mmod3.1)$varcomp[[1]][3]
rDGE_IGE.1<-covDGE.IGE.1 / (vDGE.1 * vIGE.1)**.5

#Modèles mixtes lme4 (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)


lmod1 <- lmer(Largeur_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data)
summary(lmod1)
anova(lmod1)

lmod1.1 <- lmer(Largeur_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data[-outlier,])
summary(lmod1.1)
anova(lmod1.1)

lmod2 <- lmer(Largeur_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data)
summary(lmod2)
anova(lmod2)

lmod2.1 <- lmer(Largeur_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data[-outlier,])
summary(lmod2.1)
anova(lmod2.1)

lmod3 <- lmer(Largeur_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
              , data = data)
summary(lmod3)
anova(lmod3)

lmod3.1 <- lmer(Largeur_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
              , data = data[-outlier,])

summary(lmod3.1)
anova(lmod3.1)

#Plot BLUP IGE vs DGE et correlation avec outlier

BLUP<-merge(ranef(lmod1)$plante_genotype, ranef(lmod2)$voisin, by.x=0, by.y=0)
names(BLUP)<-c("EPO","DGE","IGE")

plot(BLUP$DGE,BLUP$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP))
abline(coef,col="red")
cor.test(BLUP$DGE,BLUP$IGE)

#Plot BLUP IGE vs DGE et correlation sans outlier

BLUP.1<-merge(ranef(lmod1.1)$plante_genotype, ranef(lmod2.1)$voisin, by.x=0, by.y=0)
names(BLUP.1)<-c("EPO","DGE","IGE")

plot(BLUP.1$DGE,BLUP.1$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP.1))
abline(coef,col="red")
cor.test(BLUP.1$DGE,BLUP.1$IGE)
```

```{r}
#Etude de la biomasse sèche 
#Modèles fixes (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mod0<- lm(Largeur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine,
           data=data)
summary(mod0)
anova(mod0)

mod0.1<-lm(Largeur_feuille_2~
           Bloc_M+
           Structuration_design+
           poids_graine,
           data=data[-outlier,])
summary(mod0.1)
anova(mod0.1)

mod1<-lm(Largeur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype,
           data=data)
summary(mod1)
anova(mod1)

mod1.1<-lm(Largeur_feuille_2~
           Bloc_M+
           Structuration_design+
           poids_graine+
           plante_genotype,
           data=data[-outlier,])

summary(mod1.1)
anova(mod1.1)

mod2 <- lm(Largeur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data)
summary(mod2)
anova(mod2)

mod2.1<-lm(Largeur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data[-outlier,])
summary(mod2.1)
anova(mod2.1)

mod3 <- lm(Largeur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data)
summary(mod3)
anova(mod3)

mod3.1<-lm(Largeur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data[-outlier,])
summary(mod3.1)
anova(mod3.1)

mod4 <- lm(Largeur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data)
summary(mod4)
anova(mod4)
shapiro.test(mod4$residuals)

mod4.1<-lm(Largeur_feuille_2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data[-outlier,])
summary(mod4.1)
anova(mod4.1)


#Récupération des DGE et IGE marginaux pour les modèles avec outliers.

marg_dge<-emmeans(mod4,~plante_genotype)
marg_ige<-emmeans(mod4,~voisin)

a<-as.vector(as.character(summary(marg_dge)$plante_genotype))
b<-as.vector(as.character(summary(marg_dge)$emmean ))

mean_dge<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_dge)<-c("EPO", "DGE")
mean_dge$DGE <- as.numeric(mean_dge$DGE)

a<-as.vector(as.character(summary(marg_ige)$voisin))
b<-as.vector(as.character(summary(marg_ige)$emmean ))
mean_ige<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_ige)<-c("EPO", "IGE")

BLUE<-merge(mean_dge, mean_ige, by.x=1, by.y=1 )
BLUE$DGE<-as.numeric(BLUE$DGE)
BLUE$IGE<-as.numeric(BLUE$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE$DGE,BLUE$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE))
abline(coef,col = "red")
cor.test(BLUE$DGE, BLUE$IGE)

##Récupération des DGE et IGE marginaux pour les modèles sans outliers.

marg_dge.1<-emmeans(mod1.1,~plante_genotype)
marg_ige.1<-emmeans(mod2.1,~voisin)

a.1<-as.vector(as.character(summary(marg_dge.1)$plante_genotype))
b.1<-as.vector(as.character(summary(marg_dge.1)$emmean ))

mean_dge.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_dge.1)<-c("EPO", "DGE")
mean_dge.1$DGE <- as.numeric(mean_dge.1$DGE)

a.1<-as.vector(as.character(summary(marg_ige.1)$voisin))
b.1<-as.vector(as.character(summary(marg_ige.1)$emmean ))
mean_ige.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_ige.1)<-c("EPO", "IGE")

BLUE.1<-merge(mean_dge.1, mean_ige.1, by.x=1, by.y=1 )
BLUE.1$DGE<-as.numeric(BLUE.1$DGE)
BLUE.1$IGE<-as.numeric(BLUE.1$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE.1$DGE,BLUE.1$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE.1))
abline(coef,col = "red")
cor.test(BLUE.1$DGE, BLUE.1$IGE)

#Modèles mixtes sommer (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mmod0 <- mmer(Largeur_feuille_2 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data)
summary(mmod0)
anova(mmod0)

mmod0.1 <- mmer(Largeur_feuille_2 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod0.1)
anova(mmod0.1)

mmod1 <- mmer(Largeur_feuille_2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod1)
anova(mmod1)

mmod1.1 <- mmer(Largeur_feuille_2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod1.1)
anova(mmod1.1)

mmod2 <- mmer(Largeur_feuille_2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data)
summary(mmod2)
anova(mmod2)

mmod2.1 <- mmer(Largeur_feuille_2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod2.1)
anova(mmod2.1)

mmod3 <- mmer(Largeur_feuille_2 ~ Structuration_design + Bloc_M + poids_graine,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod3)
anova(mmod3)

mmod3.1 <- mmer(Largeur_feuille_2 ~ Structuration_design + Bloc_M,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data[-outlier,])
summary(mmod3.1)
anova(mmod3.1)

#Calcul de la correlation pour les modèles à covariance

#Modèle avec outlier

vDGE<-summary(mmod3)$varcomp[[1]][1]
covDGE.IGE<-summary(mmod3)$varcomp[[1]][2]
vIGE<-summary(mmod3)$varcomp[[1]][3]
rDGE_IGE<-covDGE.IGE / (vDGE * vIGE)**.5

#Modèle sans outlier
vDGE.1<-summary(mmod3.1)$varcomp[[1]][1]
covDGE.IGE.1<-summary(mmod3.1)$varcomp[[1]][2]
vIGE.1<-summary(mmod3.1)$varcomp[[1]][3]
rDGE_IGE.1<-covDGE.IGE.1 / (vDGE.1 * vIGE.1)**.5

#Modèles mixtes lme4 (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)


lmod1 <- lmer(Largeur_feuille_2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data)
summary(lmod1)
anova(lmod1)

lmod1.1 <- lmer(Largeur_feuille_2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data[-outlier,])
summary(lmod1.1)
anova(lmod1.1)

lmod2 <- lmer(Largeur_feuille_2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data)
summary(lmod2)
anova(lmod2)

lmod2.1 <- lmer(Largeur_feuille_2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data[-outlier,])
summary(lmod2.1)
anova(lmod2.1)

lmod3 <- lmer(Largeur_feuille_2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
              , data = data)
summary(lmod3)
anova(lmod3)

lmod3.1 <- lmer(Largeur_feuille_2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
            + (1|plante_genotype:voisin)
              , data = data[-outlier,])

summary(lmod3.1)
anova(lmod3.1)

#Plot BLUP IGE vs DGE et correlation avec outlier

BLUP<-merge(ranef(lmod3)$plante_genotype, ranef(lmod3)$voisin, by.x=0, by.y=0)
names(BLUP)<-c("EPO","DGE","IGE")

plot(BLUP$DGE,BLUP$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP))
abline(coef,col="red")
cor.test(BLUP$DGE,BLUP$IGE)

#Plot BLUP IGE vs DGE et correlation sans outlier

BLUP.1<-merge(ranef(lmod1.1)$plante_genotype, ranef(lmod2.1)$voisin, by.x=0, by.y=0)
names(BLUP.1)<-c("EPO","DGE","IGE")

plot(BLUP.1$DGE,BLUP.1$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP.1))
abline(coef,col="red")
cor.test(BLUP.1$DGE,BLUP.1$IGE)
```

```{r}
#Etude de la biomasse sèche 
#Modèles fixes (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mod0<- lm(Surface_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine,
           data=data)
summary(mod0)
anova(mod0)

mod0.1<-lm(Surface_feuille_1~
           Bloc_M+
           Structuration_design+
           poids_graine,
           data=data[-outlier,])
summary(mod0.1)
anova(mod0.1)

mod1<-lm(Surface_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype,
           data=data)
summary(mod1)
anova(mod1)

mod1.1<-lm(Surface_feuille_1~
           Bloc_M+
           Structuration_design+
           poids_graine+
           plante_genotype,
           data=data[-outlier,])

summary(mod1.1)
anova(mod1.1)

mod2 <- lm(Surface_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data)
summary(mod2)
anova(mod2)

mod2.1<-lm(Surface_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data[-outlier,])
summary(mod2.1)
anova(mod2.1)

mod3 <- lm(Surface_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data)
summary(mod3)
anova(mod3)

mod3.1<-lm(Surface_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data[-outlier,])
summary(mod3.1)
anova(mod3.1)

mod4 <- lm(Surface_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data)
summary(mod4)
anova(mod4)
shapiro.test(mod4$residuals)

mod4.1<-lm(Surface_feuille_1~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data[-outlier,])
summary(mod4.1)
anova(mod4.1)


#Récupération des DGE et IGE marginaux pour les modèles avec outliers.

marg_dge<-emmeans(mod4,~plante_genotype)
marg_ige<-emmeans(mod4,~voisin)

a<-as.vector(as.character(summary(marg_dge)$plante_genotype))
b<-as.vector(as.character(summary(marg_dge)$emmean ))

mean_dge<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_dge)<-c("EPO", "DGE")
mean_dge$DGE <- as.numeric(mean_dge$DGE)

a<-as.vector(as.character(summary(marg_ige)$voisin))
b<-as.vector(as.character(summary(marg_ige)$emmean ))
mean_ige<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_ige)<-c("EPO", "IGE")

BLUE<-merge(mean_dge, mean_ige, by.x=1, by.y=1 )
BLUE$DGE<-as.numeric(BLUE$DGE)
BLUE$IGE<-as.numeric(BLUE$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE$DGE,BLUE$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE))
abline(coef,col = "red")
cor.test(BLUE$DGE, BLUE$IGE)

##Récupération des DGE et IGE marginaux pour les modèles sans outliers.

marg_dge.1<-emmeans(mod1.1,~plante_genotype)
marg_ige.1<-emmeans(mod2.1,~voisin)

a.1<-as.vector(as.character(summary(marg_dge.1)$plante_genotype))
b.1<-as.vector(as.character(summary(marg_dge.1)$emmean ))

mean_dge.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_dge.1)<-c("EPO", "DGE")
mean_dge.1$DGE <- as.numeric(mean_dge.1$DGE)

a.1<-as.vector(as.character(summary(marg_ige.1)$voisin))
b.1<-as.vector(as.character(summary(marg_ige.1)$emmean ))
mean_ige.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_ige.1)<-c("EPO", "IGE")

BLUE.1<-merge(mean_dge.1, mean_ige.1, by.x=1, by.y=1 )
BLUE.1$DGE<-as.numeric(BLUE.1$DGE)
BLUE.1$IGE<-as.numeric(BLUE.1$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE.1$DGE,BLUE.1$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE.1))
abline(coef,col = "red")
cor.test(BLUE.1$DGE, BLUE.1$IGE)

#Modèles mixtes sommer (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mmod0 <- mmer(Surface_feuille_1 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data)
summary(mmod0)
anova(mmod0)

mmod0.1 <- mmer(Surface_feuille_1 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod0.1)
anova(mmod0.1)

mmod1 <- mmer(Surface_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod1)
anova(mmod1)

mmod1.1 <- mmer(Surface_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod1.1)
anova(mmod1.1)

mmod2 <- mmer(Surface_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data)
summary(mmod2)
anova(mmod2)

mmod2.1 <- mmer(Surface_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod2.1)
anova(mmod2.1)

mmod3 <- mmer(Surface_feuille_1 ~ Structuration_design + Bloc_M + poids_graine,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod3)
anova(mmod3)

mmod3.1 <- mmer(Surface_feuille_1 ~ Structuration_design + Bloc_M,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data[-outlier,])
summary(mmod3.1)
anova(mmod3.1)

#Calcul de la correlation pour les modèles à covariance

#Modèle avec outlier

vDGE<-summary(mmod3)$varcomp[[1]][1]
covDGE.IGE<-summary(mmod3)$varcomp[[1]][2]
vIGE<-summary(mmod3)$varcomp[[1]][3]
rDGE_IGE<-covDGE.IGE / (vDGE * vIGE)**.5

#Modèle sans outlier
vDGE.1<-summary(mmod3.1)$varcomp[[1]][1]
covDGE.IGE.1<-summary(mmod3.1)$varcomp[[1]][2]
vIGE.1<-summary(mmod3.1)$varcomp[[1]][3]
rDGE_IGE.1<-covDGE.IGE.1 / (vDGE.1 * vIGE.1)**.5

#Modèles mixtes lme4 (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)


lmod1 <- lmer(Surface_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data)
summary(lmod1)
anova(lmod1)

lmod1.1 <- lmer(Surface_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data[-outlier,])
summary(lmod1.1)
anova(lmod1.1)

lmod2 <- lmer(Surface_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data)
summary(lmod2)
anova(lmod2)

lmod2.1 <- lmer(Surface_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data[-outlier,])
summary(lmod2.1)
anova(lmod2.1)

lmod3 <- lmer(Surface_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
              , data = data)
summary(lmod3)
anova(lmod3)

lmod3.1 <- lmer(Surface_feuille_1 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
            + (1|plante_genotype:voisin), data = data)

summary(lmod3.1)
anova(lmod3.1)

#Plot BLUP IGE vs DGE et correlation avec outlier

BLUP<-merge(ranef(lmod1)$plante_genotype, ranef(lmod2)$voisin, by.x=0, by.y=0)
names(BLUP)<-c("EPO","DGE","IGE")

plot(BLUP$DGE,BLUP$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP))
abline(coef,col="red")
cor.test(BLUP$DGE,BLUP$IGE)

#Plot BLUP IGE vs DGE et correlation sans outlier

BLUP.1<-merge(ranef(lmod3.1)$plante_genotype, ranef(lmod3.1)$voisin, by.x=0, by.y=0)
names(BLUP.1)<-c("EPO","DGE","IGE")

plot(BLUP.1$DGE,BLUP.1$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP.1))
abline(coef,col="red")
cor.test(BLUP.1$DGE,BLUP.1$IGE)
```

```{r}


Quant_sup_sf2<-quantile(data$log_sf2,0.99)
Quant_inf_sf2<-quantile(data$log_sf2,0.045)
outlier_sf2_idx<-which(data$log_sf2<Quant_inf_sf2|data$log_sf2>Quant_sup_sf2)
shapiro.test(log(data[-outlier_sf2_idx,]$Surface_feuille_2))

hist_sf2<-ggplot(data[-outlier_sf2_idx,],aes(log_sf2))+
  geom_histogram(aes(y=..density..),color="Blue",fill="white",binwidth =0.01)+
  geom_density(fill="Red",alpha=0.2)+
  geom_vline(aes(xintercept=Quant_inf_sf2),color="red")+
  geom_vline(aes(xintercept=Quant_sup_sf2),color="red")
hist_sf2
#Etude de la biomasse sèche 
#Modèles fixes (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mod0<- lm(log_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine,
           data=data)
summary(mod0)
anova(mod0)

mod0.1<-lm(log_sf2~
           Bloc_M+
           Structuration_design+
           poids_graine,
           data=data[-outlier,])
summary(mod0.1)
anova(mod0.1)

mod1<-lm(log_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype,
           data=data)
summary(mod1)
anova(mod1)

mod1.1<-lm(log_sf2~
           Bloc_M+
           Structuration_design+
           poids_graine+
           plante_genotype,
           data=data[-outlier,])

summary(mod1.1)
anova(mod1.1)

mod2 <- lm(log_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data)
summary(mod2)
anova(mod2)

mod2.1<-lm(log_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data[-outlier,])
summary(mod2.1)
anova(mod2.1)

mod3 <- lm(log_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data)
summary(mod3)
anova(mod3)

mod3.1<-lm(log_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data[-outlier,])
summary(mod3.1)
anova(mod3.1)

mod4 <- lm(log_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data)
summary(mod4)
anova(mod4)

mod4.1<-lm(log_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data[-outlier,])
summary(mod4.1)
anova(mod4.1)


#Récupération des DGE et IGE marginaux pour les modèles avec outliers.

marg_dge<-emmeans(mod1,~plante_genotype)
marg_ige<-emmeans(mod2,~voisin)

a<-as.vector(as.character(summary(marg_dge)$plante_genotype))
b<-as.vector(as.character(summary(marg_dge)$emmean ))

mean_dge<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_dge)<-c("EPO", "DGE")
mean_dge$DGE <- as.numeric(mean_dge$DGE)

a<-as.vector(as.character(summary(marg_ige)$voisin))
b<-as.vector(as.character(summary(marg_ige)$emmean ))
mean_ige<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_ige)<-c("EPO", "IGE")

BLUE<-merge(mean_dge, mean_ige, by.x=1, by.y=1 )
BLUE$DGE<-as.numeric(BLUE$DGE)
BLUE$IGE<-as.numeric(BLUE$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE$DGE,BLUE$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE))
abline(coef,col = "red")
cor.test(BLUE$DGE, BLUE$IGE)

##Récupération des DGE et IGE marginaux pour les modèles sans outliers.

marg_dge.1<-emmeans(mod1.1,~plante_genotype)
marg_ige.1<-emmeans(mod2.1,~voisin)

a.1<-as.vector(as.character(summary(marg_dge.1)$plante_genotype))
b.1<-as.vector(as.character(summary(marg_dge.1)$emmean ))

mean_dge.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_dge.1)<-c("EPO", "DGE")
mean_dge.1$DGE <- as.numeric(mean_dge.1$DGE)

a.1<-as.vector(as.character(summary(marg_ige.1)$voisin))
b.1<-as.vector(as.character(summary(marg_ige.1)$emmean ))
mean_ige.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_ige.1)<-c("EPO", "IGE")

BLUE.1<-merge(mean_dge.1, mean_ige.1, by.x=1, by.y=1 )
BLUE.1$DGE<-as.numeric(BLUE.1$DGE)
BLUE.1$IGE<-as.numeric(BLUE.1$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE.1$DGE,BLUE.1$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE.1))
abline(coef,col = "red")
cor.test(BLUE.1$DGE, BLUE.1$IGE)

#Modèles mixtes sommer (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mmod0 <- mmer(log_sf2 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data)
summary(mmod0)
anova(mmod0)

mmod0.1 <- mmer(log_sf2 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod0.1)
anova(mmod0.1)

mmod1 <- mmer(log_sf2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod1)
anova(mmod1)

mmod1.1 <- mmer(log_sf2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod1.1)
anova(mmod1.1)

mmod2 <- mmer(log_sf2 ~ Structuration_design + Bloc_M + poids_graine,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data)
summary(mmod2)
anova(mmod2)

mmod2.1 <- mmer(log_sf2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod2.1)
anova(mmod2.1)

mmod3 <- mmer(log_sf2 ~ Structuration_design + Bloc_M + poids_graine,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod3)
anova(mmod3)

mmod3.1 <- mmer(log_sf2 ~ Structuration_design + Bloc_M,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data[-outlier,])
summary(mmod3.1)
anova(mmod3.1)

#Calcul de la correlation pour les modèles à covariance

#Modèle avec outlier

vDGE<-summary(mmod3)$varcomp[[1]][1]
covDGE.IGE<-summary(mmod3)$varcomp[[1]][2]
vIGE<-summary(mmod3)$varcomp[[1]][3]
rDGE_IGE<-covDGE.IGE / (vDGE * vIGE)**.5

blupDGE_v=mmod2$U$`plante_genotype`$log_sf2
blupIGE_v=mmod2$U$`voisin`$log_sf2
blupDIGE_v=modDGE_v$U$`plante_genotype:voisin`$Longueur_feuille_2

plot(blupDGE_v,blupIGE_v)
cor(blupDGE_v,blupIGE_v)

#Modèle sans outlier
vDGE.1<-summary(mmod3.1)$varcomp[[1]][1]
covDGE.IGE.1<-summary(mmod3.1)$varcomp[[1]][2]
vIGE.1<-summary(mmod3.1)$varcomp[[1]][3]
rDGE_IGE.1<-covDGE.IGE.1 / (vDGE.1 * vIGE.1)**.5

#Modèles mixtes lme4 (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)


lmod1 <- lmer(log_sf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data)
summary(lmod1)
anova(lmod1)

lmod1.1 <- lmer(log_sf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data[-outlier,])
summary(lmod1.1)
anova(lmod1.1)

lmod2 <- lmer(log_sf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data)
summary(lmod2)
anova(lmod2)

lmod2.1 <- lmer(log_sf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data[-outlier,])
summary(lmod2.1)
anova(lmod2.1)

lmod3 <- lmer(log_sf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
              , data = data)
summary(lmod3)
anova(lmod3)

lmod3.1 <- lmer(log_sf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
            + (1|plante_genotype:voisin)
              , data = data[-outlier,])

summary(lmod3.1)
anova(lmod3.1)

#Plot BLUP IGE vs DGE et correlation avec outlier

BLUP<-merge(ranef(lmod1)$plante_genotype, ranef(lmod2)$voisin, by.x=0, by.y=0)
names(BLUP)<-c("EPO","DGE","IGE")

plot(BLUP$DGE,BLUP$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP))
abline(coef,col="red")
cor.test(BLUP$DGE,BLUP$IGE)

#Plot BLUP IGE vs DGE et correlation sans outlier

BLUP.1<-merge(ranef(lmod1.1)$plante_genotype, ranef(lmod2.1)$voisin, by.x=0, by.y=0)
names(BLUP.1)<-c("EPO","DGE","IGE")

plot(BLUP.1$DGE,BLUP.1$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP.1))
abline(coef,col="red")
cor.test(BLUP.1$DGE,BLUP.1$IGE)
```


```{r}
Quant_sup_sf2<-quantile(data$sqrt_sf2,0.99)
Quant_inf_sf2<-quantile(data$sqrt_sf2,0.045)
outlier_sf2_idx<-which(data$sqrt_sf2<Quant_inf_sf2|data$sqrt_sf2>Quant_sup_sf2)
shapiro.test(log(data[-outlier_sf2_idx,]$Surface_feuille_2))

hist_sf2<-ggplot(data,aes(sqrt_sf2))+
  geom_histogram(aes(y=..density..),color="Blue",fill="white",binwidth =0.01)+
  geom_density(fill="Red",alpha=0.2)+
  geom_vline(aes(xintercept=Quant_inf_sf2),color="red")+
  geom_vline(aes(xintercept=Quant_sup_sf2),color="red")
hist_sf2
#Etude de la biomasse sèche 
#Modèles fixes (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mod0<- lm(sqrt_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine,
           data=data)
summary(mod0)
anova(mod0)

mod0.1<-lm(sqrt_sf2~
           Bloc_M+
           Structuration_design+
           poids_graine,
           data=data[-outlier,])
summary(mod0.1)
anova(mod0.1)

mod1<-lm(sqrt_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype,
           data=data)
summary(mod1)
anova(mod1)

mod1.1<-lm(sqrt_sf2~
           Bloc_M+
           Structuration_design+
           poids_graine+
           plante_genotype,
           data=data[-outlier,])

summary(mod1.1)
anova(mod1.1)

mod2 <- lm(sqrt_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data)
summary(mod2)
anova(mod2)

mod2.1<-lm(sqrt_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data[-outlier,])
summary(mod2.1)
anova(mod2.1)

mod3 <- lm(sqrt_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data)
summary(mod3)
anova(mod3)

mod3.1<-lm(sqrt_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data[-outlier,])
summary(mod3.1)
anova(mod3.1)

mod4 <- lm(sqrt_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data)
summary(mod4)
anova(mod4)

mod4.1<-lm(sqrt_sf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data[-outlier,])
summary(mod4.1)
anova(mod4.1)


#Récupération des DGE et IGE marginaux pour les modèles avec outliers.

marg_dge<-emmeans(mod1,~plante_genotype)
marg_ige<-emmeans(mod2,~voisin)

a<-as.vector(as.character(summary(marg_dge)$plante_genotype))
b<-as.vector(as.character(summary(marg_dge)$emmean ))

mean_dge<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_dge)<-c("EPO", "DGE")
mean_dge$DGE <- as.numeric(mean_dge$DGE)

a<-as.vector(as.character(summary(marg_ige)$voisin))
b<-as.vector(as.character(summary(marg_ige)$emmean ))
mean_ige<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_ige)<-c("EPO", "IGE")

BLUE<-merge(mean_dge, mean_ige, by.x=1, by.y=1 )
BLUE$DGE<-as.numeric(BLUE$DGE)
BLUE$IGE<-as.numeric(BLUE$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE$DGE,BLUE$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE))
abline(coef,col = "red")
cor.test(BLUE$DGE, BLUE$IGE)

##Récupération des DGE et IGE marginaux pour les modèles sans outliers.

marg_dge.1<-emmeans(mod1.1,~plante_genotype)
marg_ige.1<-emmeans(mod2.1,~voisin)

a.1<-as.vector(as.character(summary(marg_dge.1)$plante_genotype))
b.1<-as.vector(as.character(summary(marg_dge.1)$emmean ))

mean_dge.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))


names(mean_dge.1)<-c("EPO", "DGE")


mean_dge.1$DGE <- as.numeric(mean_dge.1$DGE)

a.1<-as.vector(as.character(summary(marg_ige.1)$voisin))
b.1<-as.vector(as.character(summary(marg_ige.1)$emmean ))
mean_ige.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_ige.1)<-c("EPO", "IGE")

BLUE.1<-merge(mean_dge.1, mean_ige.1, by.x=1, by.y=1 )
BLUE.1$DGE<-as.numeric(BLUE.1$DGE)
BLUE.1$IGE<-as.numeric(BLUE.1$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE.1$DGE,BLUE.1$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE.1))
abline(coef,col = "red")
cor.test(BLUE.1$DGE, BLUE.1$IGE)

#Modèles mixtes sommer (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mmod0 <- mmer(sqrt_sf2 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data)
summary(mmod0)
anova(mmod0)

mmod0.1 <- mmer(sqrt_sf2 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod0.1)
anova(mmod0.1)

mmod1 <- mmer(sqrt_sf2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod1)
anova(mmod1)

mmod1.1 <- mmer(sqrt_sf2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod1.1)
anova(mmod1.1)

mmod2 <- mmer(sqrt_sf2 ~ Structuration_design + Bloc_M + poids_graine,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data)
summary(mmod2)
anova(mmod2)

mmod2.1 <- mmer(sqrt_sf2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod2.1)
anova(mmod2.1)

mmod3 <- mmer(sqrt_sf2 ~ Structuration_design + Bloc_M + poids_graine,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod3)
anova(mmod3)

mmod3.1 <- mmer(sqrt_sf2 ~ Structuration_design + Bloc_M,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data[-outlier,])
summary(mmod3.1)
anova(mmod3.1)

#Calcul de la correlation pour les modèles à covariance

#Modèle avec outlier

vDGE<-summary(mmod3)$varcomp[[1]][1]
covDGE.IGE<-summary(mmod3)$varcomp[[1]][2]
vIGE<-summary(mmod3)$varcomp[[1]][3]
rDGE_IGE<-covDGE.IGE / (vDGE * vIGE)**.5

blupDGE_v=mmod2$U$`plante_genotype`$sqrt_sf2
blupIGE_v=mmod2$U$`voisin`$sqrt_sf2
blupDIGE_v=modDGE_v$U$`plante_genotype:voisin`$Longueur_feuille_2

plot(blupDGE_v,blupIGE_v)
cor(blupDGE_v,blupIGE_v)

#Modèle sans outlier
vDGE.1<-summary(mmod3.1)$varcomp[[1]][1]
covDGE.IGE.1<-summary(mmod3.1)$varcomp[[1]][2]
vIGE.1<-summary(mmod3.1)$varcomp[[1]][3]
rDGE_IGE.1<-covDGE.IGE.1 / (vDGE.1 * vIGE.1)**.5

#Modèles mixtes lme4 (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)


lmod1 <- lmer(sqrt_sf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data)
summary(lmod1)
anova(lmod1)

lmod1.1 <- lmer(sqrt_sf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data[-outlier,])
summary(lmod1.1)
anova(lmod1.1)

lmod2 <- lmer(sqrt_sf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data)
summary(lmod2)
anova(lmod2)

lmod2.1 <- lmer(sqrt_sf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data[-outlier,])
summary(lmod2.1)
anova(lmod2.1)

lmod3 <- lmer(sqrt_sf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
              , data = data)
summary(lmod3)
anova(lmod3)

lmod3.1 <- lmer(sqrt_sf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
            + (1|plante_genotype:voisin)
              , data = data[-outlier,])

summary(lmod3.1)
anova(lmod3.1)

#Plot BLUP IGE vs DGE et correlation avec outlier

BLUP<-merge(ranef(lmod1)$plante_genotype, ranef(lmod2)$voisin, by.x=0, by.y=0)
names(BLUP)<-c("EPO","DGE","IGE")

plot(BLUP$DGE,BLUP$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP))
abline(coef,col="red")
cor.test(BLUP$DGE,BLUP$IGE)

#Plot BLUP IGE vs DGE et correlation sans outlier

BLUP.1<-merge(ranef(lmod1.1)$plante_genotype, ranef(lmod2.1)$voisin, by.x=0, by.y=0)
names(BLUP.1)<-c("EPO","DGE","IGE")

plot(BLUP.1$DGE,BLUP.1$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP.1))
abline(coef,col="red")
cor.test(BLUP.1$DGE,BLUP.1$IGE)
```




```{r}
Quant_sup_lf2<-quantile(data$log_lf2,1)
Quant_inf_lf2<-quantile(data$log_lf2,0.02)
outlier_lf2_idx<-which(data$log_lf2<Quant_inf_lf2|data$log_lf2>Quant_sup_lf2)
shapiro.test(data[-outlier_lf2_idx,]$Longueur_feuille_2)

hist_lf2<-ggplot(data[-outlier_lf2_idx,],aes(log_lf2))+
  geom_histogram(aes(y=..density..),color="Blue",fill="white",binwidth =0.01)+
  geom_density(fill="Red",alpha=0.2)+
  geom_vline(aes(xintercept=Quant_inf_lf2),color="red")+
  geom_vline(aes(xintercept=Quant_sup_lf2),color="red")
hist_lf2
#Etude de la biomasse sèche 
#Modèles fixes (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mod0<- lm(log_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine,
           data=data)
summary(mod0)
anova(mod0)

mod0.1<-lm(log_lf2~
           Bloc_M+
           Structuration_design+
           poids_graine,
           data=data[-outlier,])
summary(mod0.1)
anova(mod0.1)

mod1<-lm(log_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype,
           data=data)
summary(mod1)
anova(mod1)

mod1.1<-lm(log_lf2~
           Bloc_M+
           Structuration_design+
           poids_graine+
           plante_genotype,
           data=data[-outlier,])

summary(mod1.1)
anova(mod1.1)

mod2 <- lm(log_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data)
summary(mod2)
anova(mod2)

mod2.1<-lm(log_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data[-outlier,])
summary(mod2.1)
anova(mod2.1)

mod3 <- lm(log_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data)
summary(mod3)
anova(mod3)

mod3.1<-lm(log_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data[-outlier,])
summary(mod3.1)
anova(mod3.1)

mod4 <- lm(log_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data)
summary(mod4)
anova(mod4)

mod4.1<-lm(log_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data[-outlier,])
summary(mod4.1)
anova(mod4.1)


#Récupération des DGE et IGE marginaux pour les modèles avec outliers.

marg_dge<-emmeans(mod1,~plante_genotype)
marg_ige<-emmeans(mod2,~voisin)

a<-as.vector(as.character(summary(marg_dge)$plante_genotype))
b<-as.vector(as.character(summary(marg_dge)$emmean ))

mean_dge<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_dge)<-c("EPO", "DGE")
mean_dge$DGE <- as.numeric(mean_dge$DGE)

a<-as.vector(as.character(summary(marg_ige)$voisin))
b<-as.vector(as.character(summary(marg_ige)$emmean ))
mean_ige<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_ige)<-c("EPO", "IGE")

BLUE<-merge(mean_dge, mean_ige, by.x=1, by.y=1 )
BLUE$DGE<-as.numeric(BLUE$DGE)
BLUE$IGE<-as.numeric(BLUE$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE$DGE,BLUE$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE))
abline(coef,col = "red")
cor.test(BLUE$DGE, BLUE$IGE)

##Récupération des DGE et IGE marginaux pour les modèles sans outliers.

marg_dge.1<-emmeans(mod1.1,~plante_genotype)
marg_ige.1<-emmeans(mod2.1,~voisin)

a.1<-as.vector(as.character(summary(marg_dge.1)$plante_genotype))
b.1<-as.vector(as.character(summary(marg_dge.1)$emmean ))

mean_dge.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_dge.1)<-c("EPO", "DGE")
mean_dge.1$DGE <- as.numeric(mean_dge.1$DGE)

a.1<-as.vector(as.character(summary(marg_ige.1)$voisin))
b.1<-as.vector(as.character(summary(marg_ige.1)$emmean ))
mean_ige.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_ige.1)<-c("EPO", "IGE")

BLUE.1<-merge(mean_dge.1, mean_ige.1, by.x=1, by.y=1 )
BLUE.1$DGE<-as.numeric(BLUE.1$DGE)
BLUE.1$IGE<-as.numeric(BLUE.1$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE.1$DGE,BLUE.1$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE.1))
abline(coef,col = "red")
cor.test(BLUE.1$DGE, BLUE.1$IGE)

#Modèles mixtes sommer (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mmod0 <- mmer(log_lf2 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data)
summary(mmod0)
anova(mmod0)

mmod0.1 <- mmer(log_lf2 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod0.1)
anova(mmod0.1)

mmod1 <- mmer(log_lf2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod1)
anova(mmod1)

mmod1.1 <- mmer(log_lf2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod1.1)
anova(mmod1.1)

mmod2 <- mmer(log_lf2 ~ Structuration_design + Bloc_M + poids_graine,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data)
summary(mmod2)
anova(mmod2)

mmod2.1 <- mmer(log_lf2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod2.1)
anova(mmod2.1)

mmod3 <- mmer(log_lf2 ~ Structuration_design + Bloc_M + poids_graine,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod3)
anova(mmod3)

mmod3.1 <- mmer(log_lf2 ~ Structuration_design + Bloc_M,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data[-outlier,])
summary(mmod3.1)
anova(mmod3.1)

#Calcul de la correlation pour les modèles à covariance

#Modèle avec outlier

vDGE<-summary(mmod3)$varcomp[[1]][1]
covDGE.IGE<-summary(mmod3)$varcomp[[1]][2]
vIGE<-summary(mmod3)$varcomp[[1]][3]
rDGE_IGE<-covDGE.IGE / (vDGE * vIGE)**.5

blupDGE_v=mmod2$U$`plante_genotype`$log_lf2
blupIGE_v=mmod2$U$`voisin`$log_lf2
blupDIGE_v=modDGE_v$U$`plante_genotype:voisin`$Longueur_feuille_2

plot(blupDGE_v,blupIGE_v)
cor(blupDGE_v,blupIGE_v)

#Modèle sans outlier
vDGE.1<-summary(mmod3.1)$varcomp[[1]][1]
covDGE.IGE.1<-summary(mmod3.1)$varcomp[[1]][2]
vIGE.1<-summary(mmod3.1)$varcomp[[1]][3]
rDGE_IGE.1<-covDGE.IGE.1 / (vDGE.1 * vIGE.1)**.5

#Modèles mixtes lme4 (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)


lmod1 <- lmer(log_lf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data)
summary(lmod1)
anova(lmod1)

lmod1.1 <- lmer(log_lf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data[-outlier,])
summary(lmod1.1)
anova(lmod1.1)

lmod2 <- lmer(log_lf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data)
summary(lmod2)
anova(lmod2)

lmod2.1 <- lmer(log_lf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data[-outlier,])
summary(lmod2.1)
anova(lmod2.1)

lmod3 <- lmer(log_lf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
              , data = data)
summary(lmod3)
anova(lmod3)

lmod3.1 <- lmer(log_lf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
            + (1|plante_genotype:voisin)
              , data = data[-outlier,])

summary(lmod3.1)
anova(lmod3.1)

#Plot BLUP IGE vs DGE et correlation avec outlier

BLUP<-merge(ranef(lmod1)$plante_genotype, ranef(lmod2)$voisin, by.x=0, by.y=0)
names(BLUP)<-c("EPO","DGE","IGE")

plot(BLUP$DGE,BLUP$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP))
abline(coef,col="red")
cor.test(BLUP$DGE,BLUP$IGE)

#Plot BLUP IGE vs DGE et correlation sans outlier

BLUP.1<-merge(ranef(lmod1.1)$plante_genotype, ranef(lmod2.1)$voisin, by.x=0, by.y=0)
names(BLUP.1)<-c("EPO","DGE","IGE")

plot(BLUP.1$DGE,BLUP.1$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP.1))
abline(coef,col="red")
cor.test(BLUP.1$DGE,BLUP.1$IGE)
```


```{r}
Quant_sup_lf2<-quantile(data$sqrt_lf2,0.99)
Quant_inf_lf2<-quantile(data$sqrt_lf2,0.045)
outlier_lf2_idx<-which(data$sqrt_lf2<Quant_inf_lf2|data$sqrt_lf2>Quant_sup_lf2)
shapiro.test(log(data[-outlier_lf2_idx,]$Surface_feuille_2))

hist_lf2<-ggplot(data,aes(sqrt_lf2))+
  geom_histogram(aes(y=..density..),color="Blue",fill="white",binwidth =0.01)+
  geom_density(fill="Red",alpha=0.2)+
  geom_vline(aes(xintercept=Quant_inf_lf2),color="red")+
  geom_vline(aes(xintercept=Quant_sup_lf2),color="red")
hist_lf2
#Etude de la biomasse sèche 
#Modèles fixes (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mod0<- lm(sqrt_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine,
           data=data)
summary(mod0)
anova(mod0)

mod0.1<-lm(sqrt_lf2~
           Bloc_M+
           Structuration_design+
           poids_graine,
           data=data[-outlier,])
summary(mod0.1)
anova(mod0.1)

mod1<-lm(sqrt_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype,
           data=data)
summary(mod1)
anova(mod1)

mod1.1<-lm(sqrt_lf2~
           Bloc_M+
           Structuration_design+
           poids_graine+
           plante_genotype,
           data=data[-outlier,])

summary(mod1.1)
anova(mod1.1)

mod2 <- lm(sqrt_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data)
summary(mod2)
anova(mod2)

mod2.1<-lm(sqrt_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           voisin,
           data=data[-outlier,])
summary(mod2.1)
anova(mod2.1)

mod3 <- lm(sqrt_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data)
summary(mod3)
anova(mod3)

mod3.1<-lm(sqrt_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype+
           voisin,
           data=data[-outlier,])
summary(mod3.1)
anova(mod3.1)

mod4 <- lm(sqrt_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data)
summary(mod4)
anova(mod4)

mod4.1<-lm(sqrt_lf2~
           Structuration_design+
           Bloc_M+
           poids_graine+
           plante_genotype*
           voisin,
           data=data[-outlier,])
summary(mod4.1)
anova(mod4.1)


#Récupération des DGE et IGE marginaux pour les modèles avec outliers.

marg_dge<-emmeans(mod1,~plante_genotype)
marg_ige<-emmeans(mod2,~voisin)

a<-as.vector(as.character(summary(marg_dge)$plante_genotype))
b<-as.vector(as.character(summary(marg_dge)$emmean ))

mean_dge<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_dge)<-c("EPO", "DGE")
mean_dge$DGE <- as.numeric(mean_dge$DGE)

a<-as.vector(as.character(summary(marg_ige)$voisin))
b<-as.vector(as.character(summary(marg_ige)$emmean ))
mean_ige<-as.data.frame(cbind(a, as.numeric(b)))
names(mean_ige)<-c("EPO", "IGE")

BLUE<-merge(mean_dge, mean_ige, by.x=1, by.y=1 )
BLUE$DGE<-as.numeric(BLUE$DGE)
BLUE$IGE<-as.numeric(BLUE$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE$DGE,BLUE$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE))
abline(coef,col = "red")
cor.test(BLUE$DGE, BLUE$IGE)

##Récupération des DGE et IGE marginaux pour les modèles sans outliers.

marg_dge.1<-emmeans(mod1.1,~plante_genotype)
marg_ige.1<-emmeans(mod2.1,~voisin)

a.1<-as.vector(as.character(summary(marg_dge.1)$plante_genotype))
b.1<-as.vector(as.character(summary(marg_dge.1)$emmean ))

mean_dge.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))


names(mean_dge.1)<-c("EPO", "DGE")


mean_dge.1$DGE <- as.numeric(mean_dge.1$DGE)

a.1<-as.vector(as.character(summary(marg_ige.1)$voisin))
b.1<-as.vector(as.character(summary(marg_ige.1)$emmean ))
mean_ige.1<-as.data.frame(cbind(a.1, as.numeric(b.1)))
names(mean_ige.1)<-c("EPO", "IGE")

BLUE.1<-merge(mean_dge.1, mean_ige.1, by.x=1, by.y=1 )
BLUE.1$DGE<-as.numeric(BLUE.1$DGE)
BLUE.1$IGE<-as.numeric(BLUE.1$IGE)

#Plot BLUES DGE vs IGE avec les outliers

plot(BLUE.1$DGE,BLUE.1$IGE)
coef = coefficients(lm(DGE~IGE,data = BLUE.1))
abline(coef,col = "red")
cor.test(BLUE.1$DGE, BLUE.1$IGE)

#Modèles mixtes sommer (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)

mmod0 <- mmer(sqrt_lf2 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data)
summary(mmod0)
anova(mmod0)

mmod0.1 <- mmer(sqrt_lf2 ~ 
                Structuration_design 
              + Bloc_M 
              + poids_graine,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod0.1)
anova(mmod0.1)

mmod1 <- mmer(sqrt_lf2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod1)
anova(mmod1)

mmod1.1 <- mmer(sqrt_lf2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod1.1)
anova(mmod1.1)

mmod2 <- mmer(sqrt_lf2 ~ Structuration_design + Bloc_M + poids_graine,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data)
summary(mmod2)
anova(mmod2)

mmod2.1 <- mmer(sqrt_lf2 ~ Structuration_design + Bloc_M,
                 random = ~ plante_genotype+voisin,
                 iters = 10,
                 data = data[-outlier,])
summary(mmod2.1)
anova(mmod2.1)

mmod3 <- mmer(sqrt_lf2 ~ Structuration_design + Bloc_M + poids_graine,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data)
summary(mmod3)
anova(mmod3)

mmod3.1 <- mmer(sqrt_lf2 ~ Structuration_design + Bloc_M,
                 random = ~ gvs(plante_genotype,voisin),
                 rcov = ~ units, iters = 10,
                 data = data[-outlier,])
summary(mmod3.1)
anova(mmod3.1)

#Calcul de la correlation pour les modèles à covariance

#Modèle avec outlier

vDGE<-summary(mmod3)$varcomp[[1]][1]
covDGE.IGE<-summary(mmod3)$varcomp[[1]][2]
vIGE<-summary(mmod3)$varcomp[[1]][3]
rDGE_IGE<-covDGE.IGE / (vDGE * vIGE)**.5

blupDGE_v=mmod2$U$`plante_genotype`$sqrt_lf2
blupIGE_v=mmod2$U$`voisin`$sqrt_lf2
blupDIGE_v=modDGE_v$U$`plante_genotype:voisin`$Longueur_feuille_2

plot(blupDGE_v,blupIGE_v)
cor(blupDGE_v,blupIGE_v)

#Modèle sans outlier
vDGE.1<-summary(mmod3.1)$varcomp[[1]][1]
covDGE.IGE.1<-summary(mmod3.1)$varcomp[[1]][2]
vIGE.1<-summary(mmod3.1)$varcomp[[1]][3]
rDGE_IGE.1<-covDGE.IGE.1 / (vDGE.1 * vIGE.1)**.5

#Modèles mixtes lme4 (les modèles 0.1,1.1,2.1 et 3.1 ont les outliers retirés)


lmod1 <- lmer(sqrt_lf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data)
summary(lmod1)
anova(lmod1)

lmod1.1 <- lmer(sqrt_lf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
              , data = data[-outlier,])
summary(lmod1.1)
anova(lmod1.1)

lmod2 <- lmer(sqrt_lf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data)
summary(lmod2)
anova(lmod2)

lmod2.1 <- lmer(sqrt_lf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|voisin)
              , data = data[-outlier,])
summary(lmod2.1)
anova(lmod2.1)

lmod3 <- lmer(sqrt_lf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
              , data = data)
summary(lmod3)
anova(lmod3)

lmod3.1 <- lmer(sqrt_lf2 ~
              Structuration_design
            + Bloc_M
            + poids_graine
            + (1|plante_genotype)
            + (1|voisin)
            + (1|plante_genotype:voisin)
              , data = data[-outlier,])

summary(lmod3.1)
anova(lmod3.1)

#Plot BLUP IGE vs DGE et correlation avec outlier

BLUP<-merge(ranef(lmod1)$plante_genotype, ranef(lmod2)$voisin, by.x=0, by.y=0)
names(BLUP)<-c("EPO","DGE","IGE")

plot(BLUP$DGE,BLUP$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP))
abline(coef,col="red")
cor.test(BLUP$DGE,BLUP$IGE)

#Plot BLUP IGE vs DGE et correlation sans outlier

BLUP.1<-merge(ranef(lmod1.1)$plante_genotype, ranef(lmod2.1)$voisin, by.x=0, by.y=0)
names(BLUP.1)<-c("EPO","DGE","IGE")

plot(BLUP.1$DGE,BLUP.1$IGE)
coef<-coefficients(lm(DGE~IGE,data=BLUP.1))
abline(coef,col="red")
cor.test(BLUP.1$DGE,BLUP.1$IGE)
```

















